### ISSUE TITLE
bug with @glimmer/tracking in devDependencies

### ISSUE THREAD

**Issue by alexparker** [cloudcreativity/ember-quill#2]
I installed the package, but am getting this error when building my app:

```
tried to import "@glimmer/tracking" from addon code, but "@glimmer/tracking" is a devDependency. You may need to move it into dependencies.
```
From the discord server
> But addons should put anything they use from the code they contribute to the app in dependencies.

If it helps, here is the error at length from the log file:
```
  VERSIONS:
  - ares: 1.16.1
  - brotli: 1.0.9
  - cldr: 37.0
  - icu: 67.1
  - llhttp: 2.1.3
  - modules: 83
  - napi: 7
  - nghttp2: 1.41.0
  - node: 14.15.4
  - openssl: 1.1.1i
  - tz: 2020a
  - unicode: 13.0
  - uv: 1.40.0
  - v8: 8.4.371.19-node.17
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: @cloudcreativity/ember-quill tried to import "@glimmer/tracking" from addon code, but "@glimmer/tracking" is a devDependency. You may need to move it into dependencies.
    at Package.assertAllowedDependency (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/package.js:180:19)
    at Package.resolve (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/package.js:169:14)
    at Splitter.<anonymous> (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:76:38)
    at Generator.next (<anonymous>:null:null)
    at /Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:8:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:4:12)
    at Splitter.handleLiteralImport (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:75:16)
    at Splitter.<anonymous> (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:65:32)
    at Generator.next (<anonymous>:null:null)
    at /Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:8:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:4:12)
    at /Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:63:52
    at Array.map (<anonymous>:null:null)
    at Splitter.<anonymous> (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:63:39)
    at Generator.next (<anonymous>:null:null)
    at /Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:8:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:4:12)
    at Splitter.computeTargets (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:59:16)
    at Splitter.<anonymous> (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:178:38)
    at Generator.next (<anonymous>:null:null)
    at /Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:8:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:4:12)
    at Splitter.computeDeps (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:177:16)
    at Splitter.<anonymous> (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:44:44)
    at Generator.next (<anonymous>:null:null)
    at /Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:8:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:4:12)
    at Splitter.deps (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:42:16)
    at Bundler.<anonymous> (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/bundler.js:86:45)
    at Generator.next (<anonymous>:null:null)
    at /Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/bundler.js:14:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/bundler.js:10:12)
    at Bundler.build (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/bundler.js:82:16)
    at TransformNodeWrapper.build (/Users/alexparker/code/fitspace/ui/node_modules/broccoli/dist/wrappers/transform-node.js:71:39)
    at /Users/alexparker/code/fitspace/ui/node_modules/broccoli/dist/builder.js:185:30
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Builder.build (/Users/alexparker/code/fitspace/ui/node_modules/broccoli/dist/builder.js:204:13)

  - code: [undefined]
  - codeFrame: @cloudcreativity/ember-quill tried to import "@glimmer/tracking" from addon code, but "@glimmer/tracking" is a devDependency. You may need to move it into dependencies.
  - errorMessage: @cloudcreativity/ember-quill tried to import "@glimmer/tracking" from addon code, but "@glimmer/tracking" is a devDependency. You may need to move it into dependencies.
        at Bundler
-~- created here: -~-
    at new Plugin (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new Bundler (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/bundler.js:34:9)
    at AutoImport.makeBundler (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/auto-import.js:57:16)
    at AutoImport.addTo (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/auto-import.js:67:38)
    at EmberApp.host.addonPostprocessTree (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/auto-import.js:101:29)
    at EmberApp.toTree (/Users/alexparker/code/fitspace/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1788:17)
    at module.exports (/Users/alexparker/code/fitspace/ui/ember-cli-build.js:38:14)
    at Builder.readBuildFile (/Users/alexparker/code/fitspace/ui/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/alexparker/code/fitspace/ui/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/alexparker/code/fitspace/ui/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/Users/alexparker/code/fitspace/ui/node_modules/ember-cli/lib/tasks/serve.js:49:7)
    at /Users/alexparker/code/fitspace/ui/node_modules/ember-cli/lib/models/command.js:239:24
    at tryCatcher (/Users/alexparker/code/fitspace/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/Users/alexparker/code/fitspace/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:498:33)
    at /Users/alexparker/code/fitspace/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:562:16
    at flush (/Users/alexparker/code/fitspace/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2441:7)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: @cloudcreativity/ember-quill tried to import "@glimmer/tracking" from addon code, but "@glimmer/tracking" is a devDependency. You may need to move it into dependencies.
        at Bundler
-~- created here: -~-
    at new Plugin (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new Bundler (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/bundler.js:34:9)
    at AutoImport.makeBundler (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/auto-import.js:57:16)
    at AutoImport.addTo (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/auto-import.js:67:38)
    at EmberApp.host.addonPostprocessTree (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/auto-import.js:101:29)
    at EmberApp.toTree (/Users/alexparker/code/fitspace/ui/node_modules/ember-cli/lib/broccoli/ember-app.js:1788:17)
    at module.exports (/Users/alexparker/code/fitspace/ui/ember-cli-build.js:38:14)
    at Builder.readBuildFile (/Users/alexparker/code/fitspace/ui/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/alexparker/code/fitspace/ui/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/alexparker/code/fitspace/ui/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/Users/alexparker/code/fitspace/ui/node_modules/ember-cli/lib/tasks/serve.js:49:7)
    at /Users/alexparker/code/fitspace/ui/node_modules/ember-cli/lib/models/command.js:239:24
    at tryCatcher (/Users/alexparker/code/fitspace/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/Users/alexparker/code/fitspace/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:498:33)
    at /Users/alexparker/code/fitspace/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:562:16
    at flush (/Users/alexparker/code/fitspace/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2441:7)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

-~- (end) -~-
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: Bundler
  - originalErrorMessage: @cloudcreativity/ember-quill tried to import "@glimmer/tracking" from addon code, but "@glimmer/tracking" is a devDependency. You may need to move it into dependencies.
  - stack: Error: @cloudcreativity/ember-quill tried to import "@glimmer/tracking" from addon code, but "@glimmer/tracking" is a devDependency. You may need to move it into dependencies.
    at Package.assertAllowedDependency (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/package.js:180:19)
    at Package.resolve (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/package.js:169:14)
    at Splitter.<anonymous> (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:76:38)
    at Generator.next (<anonymous>:null:null)
    at /Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:8:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:4:12)
    at Splitter.handleLiteralImport (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:75:16)
    at Splitter.<anonymous> (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:65:32)
    at Generator.next (<anonymous>:null:null)
    at /Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:8:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:4:12)
    at /Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:63:52
    at Array.map (<anonymous>:null:null)
    at Splitter.<anonymous> (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:63:39)
    at Generator.next (<anonymous>:null:null)
    at /Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:8:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:4:12)
    at Splitter.computeTargets (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:59:16)
    at Splitter.<anonymous> (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:178:38)
    at Generator.next (<anonymous>:null:null)
    at /Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:8:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:4:12)
    at Splitter.computeDeps (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:177:16)
    at Splitter.<anonymous> (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:44:44)
    at Generator.next (<anonymous>:null:null)
    at /Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:8:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:4:12)
    at Splitter.deps (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/splitter.js:42:16)
    at Bundler.<anonymous> (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/bundler.js:86:45)
    at Generator.next (<anonymous>:null:null)
    at /Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/bundler.js:14:71
    at new Promise (<anonymous>:null:null)
    at __awaiter (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/bundler.js:10:12)
    at Bundler.build (/Users/alexparker/code/fitspace/ui/node_modules/@cloudcreativity/ember-quill/node_modules/ember-auto-import/js/bundler.js:82:16)
    at TransformNodeWrapper.build (/Users/alexparker/code/fitspace/ui/node_modules/broccoli/dist/wrappers/transform-node.js:71:39)
    at /Users/alexparker/code/fitspace/ui/node_modules/broccoli/dist/builder.js:185:30
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Builder.build (/Users/alexparker/code/fitspace/ui/node_modules/broccoli/dist/builder.js:204:13)

```

**Comment by lindyhopchris** [comment]
Hey! Thanks for raising this. Hadn't noticed I think because the apps I've installed the addon into already have glimmer tracking.

I'll see when I have time to fix, but in the meantime if you wanted to submit a PR that would help.

**Comment by lindyhopchris** [comment]
@alexparker I've just published `1.0.0-alpha.2` which should fix your issue. Could you confirm?

**Comment by alexparker** [comment]
Just installed it, and retried it. That seems to have worked for me. Thank you! 🙏🏼 
reference: https://github.com/cloudcreativity/ember-quill/commit/1cb63dff19016d92aed6fd43640789eac44045e7

**Comment by lindyhopchris** [comment]
Great, thanks for confirming!
